version: '3.8'
services:
  web:
    build: .
    volumes:
      - ./source-code:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mysql
    restart: always
    volumes:
      - ./db-data:/var/lib/mysql
      - ./lab08.sql:/docker-entrypoint-initdb.d/lab08.sql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: lab08
    ports:
      - 3306:3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
